

#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <bcrypt.h>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <fstream>
#include <regex>
#include <sstream>
#include <string>
#include <vector>

#pragma comment(lib, "bcrypt.lib")

namespace
{

constexpr size_t kStubSize = 21;

constexpr uint8_t kStubTemplate[kStubSize] = {
    0x48, 0x8D, 0x35, 0x0E, 0x00, 0x00, 0x00, 0xB9, 0x00, 0x00, 0x00,
    0x00, 0xB2, 0x00, 0x30, 0x16, 0x48, 0xFF, 0xC6, 0xE2, 0xF9,
};
constexpr size_t kStubSizeOff = 8;

bool read_file(const std::string& path, std::string& out)
{
    std::ifstream f(path, std::ios::binary);
    if (!f)
        return false;
    std::ostringstream ss;
    ss << f.rdbuf();
    out = ss.str();
    return true;
}

bool write_file(const std::string& path, const std::string& content)
{
    std::ofstream f(path, std::ios::binary | std::ios::trunc);
    if (!f)
        return false;
    f.write(content.data(), static_cast<std::streamsize>(content.size()));
    return static_cast<bool>(f);
}

bool parse_plaintext_header(const std::string&    text,
                            std::string&          out_name,
                            size_t&               out_declared_size,
                            std::vector<uint8_t>& out_bytes)
{
    std::regex  header_re(R"(constexpr\s+size_t\s+(\w+)_size\s*=\s*(\d+)\s*;\s*)"
                          R"(constexpr\s+uint8_t\s+\1\s*\[\s*\d+\s*\]\s*=\s*\{)");
    std::smatch m;
    if (!std::regex_search(text, m, header_re))
        return false;
    out_name          = m[1].str();
    out_declared_size = static_cast<size_t>(std::stoull(m[2].str()));

    std::regex byte_re(R"(0x([0-9A-Fa-f]{2})\b)");
    for (auto it = std::sregex_iterator(text.begin(), text.end(), byte_re); it != std::sregex_iterator(); ++it)
    {
        out_bytes.push_back(static_cast<uint8_t>(std::stoul((*it)[1].str(), nullptr, 16)));
    }
    return true;
}

bool looks_already_encrypted(const std::vector<uint8_t>& bytes)
{
    if (bytes.size() < kStubSize)
        return false;

    for (size_t i = 0; i < kStubSize; ++i)
    {
        if (i >= kStubSizeOff && i < kStubSizeOff + 4)
            continue;
        if (i == 13)
            continue;
        if (bytes[i] != kStubTemplate[i])
            return false;
    }
    return true;
}

bool random_nonzero_key(uint8_t& out)
{
    for (int tries = 0; tries < 16; ++tries)
    {
        uint8_t  b = 0;
        NTSTATUS s = BCryptGenRandom(nullptr, &b, 1, BCRYPT_USE_SYSTEM_PREFERRED_RNG);
        if (s < 0)
            return false;
        if (b != 0)
        {
            out = b;
            return true;
        }
    }

    out = 0x7A;
    return true;
}

std::string emit_encrypted_header(const std::string& array_name, const std::vector<uint8_t>& blob)
{
    std::ostringstream out;
    out << "// Auto-generated by mvm_encrypt.exe -- do not edit.\n"
        << "// Format: 21-byte self-decryption stub (byte 13 = 0x00, patched\n"
        << "// by the HV at load time) + XOR-encrypted payload.\n"
        << "// Loaded with MICROVM_FLAG_PRE_ENCRYPTED; pass " << array_name << "_key (from " << array_name
        << ".mvm_key.h) to LoadPayload().\n"
        << "#pragma once\n"
        << "#include <cstdint>\n\n"
        << "constexpr size_t " << array_name << "_size = " << blob.size() << ";\n\n"
        << "constexpr uint8_t " << array_name << "[" << blob.size() << "] = {\n    ";
    for (size_t i = 0; i < blob.size(); ++i)
    {
        char buf[8];
        std::snprintf(buf, sizeof(buf), "0x%02X, ", blob[i]);
        out << buf;
        if ((i + 1) % 12 == 0)
            out << "\n    ";
    }
    out << "\n};\n";
    return out.str();
}

std::string emit_key_header(const std::string& array_name, uint8_t key)
{
    std::ostringstream out;
    out << "// Auto-generated by mvm_encrypt.exe -- do not edit.\n"
        << "// Companion key for " << array_name << ".mvm.h. Pass this to\n"
        << "// MicroVM::LoadPayload(..., " << array_name << "_key). The HV\n"
        << "// patches it into the stub's `mov dl, imm8` byte at load time\n"
        << "// so the key never sits adjacent to the ciphertext in .rdata.\n"
        << "#pragma once\n"
        << "#include <cstdint>\n\n";
    char buf[16];
    std::snprintf(buf, sizeof(buf), "0x%02X", key);
    out << "constexpr uint8_t " << array_name << "_key = " << buf << ";\n";
    return out.str();
}

std::string key_header_path(const std::string& mvm_h_path)
{
    static const std::string suffix = ".mvm.h";
    if (mvm_h_path.size() >= suffix.size() &&
        mvm_h_path.compare(mvm_h_path.size() - suffix.size(), suffix.size(), suffix) == 0)
    {
        return mvm_h_path.substr(0, mvm_h_path.size() - suffix.size()) + ".mvm_key.h";
    }

    return mvm_h_path + "_key.h";
}

}

int main(int argc, char** argv)
{
    if (argc != 2)
    {
        std::fprintf(stderr,
                     "Usage: mvm_encrypt.exe <path\\to\\name.mvm.h>\n"
                     "\n"
                     "Rewrites the .mvm.h in place with the pre-encrypted blob and\n"
                     "emits <name>.mvm_key.h next to it.\n");
        return 1;
    }

    const std::string input_path = argv[1];

    std::string text;
    if (!read_file(input_path, text))
    {
        std::fprintf(stderr, "mvm_encrypt: cannot read %s\n", input_path.c_str());
        return 1;
    }

    std::string          array_name;
    size_t               declared_size = 0;
    std::vector<uint8_t> bytes;
    if (!parse_plaintext_header(text, array_name, declared_size, bytes))
    {
        std::fprintf(stderr,
                     "mvm_encrypt: %s does not look like a bin2h header "
                     "(no `constexpr uint8_t <name>[N] = { ... }` match)\n",
                     input_path.c_str());
        return 1;
    }
    if (bytes.size() != declared_size)
    {
        std::fprintf(stderr,
                     "mvm_encrypt: parsed %zu byte literals but header declares %zu in %s\n",
                     bytes.size(),
                     declared_size,
                     input_path.c_str());
        return 1;
    }
    if (looks_already_encrypted(bytes))
    {
        std::fprintf(stderr,
                     "mvm_encrypt: %s already begins with the decryption stub prefix "
                     "-- refusing to double-encrypt. Delete the file and re-run "
                     "extract_text_and_bin2h.py if you want to start over.\n",
                     input_path.c_str());
        return 1;
    }
    if (declared_size == 0)
    {
        std::fprintf(stderr, "mvm_encrypt: %s has zero-length payload\n", input_path.c_str());
        return 1;
    }
    if (declared_size > 0xFFFFFFFFull)
    {
        std::fprintf(stderr, "mvm_encrypt: payload too large for the stub's u32 size field: %zu\n", declared_size);
        return 1;
    }

    uint8_t key = 0;
    if (!random_nonzero_key(key))
    {
        std::fprintf(stderr, "mvm_encrypt: BCryptGenRandom failed\n");
        return 1;
    }

    std::vector<uint8_t> blob(kStubSize + declared_size, 0);
    std::memcpy(blob.data(), kStubTemplate, kStubSize);
    const uint32_t sz32    = static_cast<uint32_t>(declared_size);
    blob[kStubSizeOff + 0] = static_cast<uint8_t>(sz32);
    blob[kStubSizeOff + 1] = static_cast<uint8_t>(sz32 >> 8);
    blob[kStubSizeOff + 2] = static_cast<uint8_t>(sz32 >> 16);
    blob[kStubSizeOff + 3] = static_cast<uint8_t>(sz32 >> 24);

    for (size_t i = 0; i < declared_size; ++i)
    {
        blob[kStubSize + i] = static_cast<uint8_t>(bytes[i] ^ key);
    }

    const std::string encrypted_h = emit_encrypted_header(array_name, blob);
    if (!write_file(input_path, encrypted_h))
    {
        std::fprintf(stderr, "mvm_encrypt: failed to write %s\n", input_path.c_str());
        return 1;
    }

    const std::string key_path = key_header_path(input_path);
    const std::string key_h    = emit_key_header(array_name, key);
    if (!write_file(key_path, key_h))
    {
        std::fprintf(stderr, "mvm_encrypt: failed to write %s\n", key_path.c_str());
        return 1;
    }

    std::printf("mvm_encrypt: %s -> %zu-byte stub + %zu-byte ciphertext (key 0x%02X); "
                "key header %s\n",
                input_path.c_str(),
                kStubSize,
                declared_size,
                key,
                key_path.c_str());
    return 0;
}
