

#pragma once
#include <cstdint>

#define LOCAL_APIC_BASE 0xFEE00000ULL

#define XAPIC_ICR_LOW_OFFSET  0x300
#define XAPIC_ICR_HIGH_OFFSET 0x310

#define ICR_DELIVERY_MODE_MASK           (7u << 8)
#define ICR_DELIVERY_MODE_SHIFT          8
#define LOCAL_APIC_DELIVERY_MODE_FIXED   0
#define LOCAL_APIC_DELIVERY_MODE_SMI     2
#define LOCAL_APIC_DELIVERY_MODE_NMI     4
#define LOCAL_APIC_DELIVERY_MODE_INIT    5
#define LOCAL_APIC_DELIVERY_MODE_STARTUP 6
