import sys
import os

def main():
    if len(sys.argv) < 4:
        print("Usage: python bin2h.py <input_bin> <output_header> <array_name>")
        sys.exit(1)

    input_bin = sys.argv[1]
    output_header = sys.argv[2]
    array_name = sys.argv[3]

    if not os.path.exists(input_bin):
        print(f"Error: Input file {input_bin} not found.")
        sys.exit(1)

    with open(input_bin, 'rb') as f:
        data = f.read()

    with open(output_header, 'w') as f:
        f.write(f"// Auto-generated by bin2h.py\n")
        f.write(f"#pragma once\n")
        f.write(f"#include <cstdint>\n\n")
        f.write(f"constexpr size_t {array_name}_size = {len(data)};\n\n")
        f.write(f"constexpr uint8_t {array_name}[{len(data)}] = {{\n    ")

        for i, byte in enumerate(data):
            f.write(f"0x{byte:02X}, ")
            if (i + 1) % 12 == 0:
                f.write("\n    ")

        f.write("\n};\n")

    print(f"Successfully converted {input_bin} to {output_header} ({len(data)} bytes).")

if __name__ == '__main__':
    main()
