import sys
import struct
import os

DISCARD_SECTIONS = {'.reloc', '.pdata'}

def extract_payload(pe_file_path):
    with open(pe_file_path, 'rb') as f:
        data = f.read()

    if data[:2] != b'MZ':
        raise ValueError("Not a valid PE file")

    e_lfanew = struct.unpack('<I', data[0x3C:0x40])[0]

    if data[e_lfanew:e_lfanew+4] != b'PE\x00\x00':
        raise ValueError("Not a valid PE file")

    num_sections = struct.unpack('<H', data[e_lfanew+6:e_lfanew+8])[0]
    opt_header_size = struct.unpack('<H', data[e_lfanew+20:e_lfanew+22])[0]

    opt_header_offset = e_lfanew + 24
    magic = struct.unpack('<H', data[opt_header_offset:opt_header_offset+2])[0]
    if magic != 0x20B:
        raise ValueError("Not a PE32+ (x64) image")
    entry_rva = struct.unpack('<I', data[opt_header_offset+16:opt_header_offset+20])[0]
    image_base = struct.unpack('<Q', data[opt_header_offset+24:opt_header_offset+32])[0]

    section_table_offset = e_lfanew + 24 + opt_header_size
    sections = []
    for i in range(num_sections):
        offset = section_table_offset + (i * 40)
        name = data[offset:offset+8].rstrip(b'\x00').decode('ascii', 'replace')
        virtual_size = struct.unpack('<I', data[offset+8:offset+12])[0]
        virtual_addr = struct.unpack('<I', data[offset+12:offset+16])[0]
        raw_size     = struct.unpack('<I', data[offset+16:offset+20])[0]
        raw_ptr      = struct.unpack('<I', data[offset+20:offset+24])[0]
        sections.append((name, virtual_addr, virtual_size, raw_size, raw_ptr))

    load = [s for s in sections
            if s[0] not in DISCARD_SECTIONS and not s[0].startswith('.debug')]
    if not load:
        raise ValueError("No loadable sections found")
    load.sort(key=lambda s: s[1])

    base_rva = load[0][1]

    if entry_rva != base_rva:
        raise ValueError(
            f"entry point RVA 0x{entry_rva:X} is not at the start of the first "
            f"loadable section '{load[0][0]}' (RVA 0x{base_rva:X}).\n"
            f"  The micro-VM starts execution at blob offset 0, so _start must be "
            f"first in .text.\n"
            f"  Link the object containing _start first and do NOT merge .rdata "
            f"into .text.")

    span_end = max(vaddr + max(vsize, raw_size)
                   for (_, vaddr, vsize, raw_size, _) in load)
    blob = bytearray(span_end - base_rva)

    for (name, vaddr, vsize, raw_size, raw_ptr) in load:
        off = vaddr - base_rva
        blob[off:off + raw_size] = data[raw_ptr:raw_ptr + raw_size]

    reloc = next((s for s in sections if s[0] == '.reloc'), None)
    applied = 0
    if reloc:
        (_, r_vaddr, r_vsize, r_raw_size, r_raw_ptr) = reloc
        raw = data[r_raw_ptr:r_raw_ptr + min(r_vsize, r_raw_size)]
        off = 0
        while off + 8 <= len(raw):
            page_rva, block_size = struct.unpack('<II', raw[off:off+8])
            if block_size < 8:
                break
            count = (block_size - 8) // 2
            for j in range(count):
                entry, = struct.unpack('<H', raw[off+8+j*2:off+10+j*2])
                rtype = entry >> 12
                roff  = entry & 0xFFF
                if rtype == 0:
                    continue
                if rtype != 10:
                    raise ValueError(
                        f"unsupported base relocation type {rtype} at RVA "
                        f"0x{page_rva + roff:X} (only DIR64 is expected in a "
                        f"freestanding x64 payload)")
                target = page_rva + roff
                boff = target - base_rva
                if boff < 0 or boff + 8 > len(blob):
                    raise ValueError(
                        f"relocation at RVA 0x{target:X} is outside the blob")
                val, = struct.unpack('<Q', blob[boff:boff+8])
                new_val = val - image_base - base_rva
                if new_val < 0:
                    raise ValueError(
                        f"relocation at RVA 0x{target:X} points outside the "
                        f"blob (VA 0x{val:X})")
                struct.pack_into('<Q', blob, boff, new_val)
                applied += 1
            off += block_size

    print(f"  base RVA=0x{base_rva:X}, span=0x{len(blob):X} bytes across "
          f"{len(load)} section(s), {applied} DIR64 relocation(s) rebased")

    return bytes(blob)

def main():
    if len(sys.argv) < 4:
        print("Usage: python extract_text_and_bin2h.py <input.exe> <output.h> <array_name>")
        sys.exit(1)

    input_exe = sys.argv[1]
    output_h = sys.argv[2]
    array_name = sys.argv[3]

    try:
        payload_data = extract_payload(input_exe)
    except Exception as e:
        print(f"Error: {e}")
        sys.exit(1)

    with open(output_h, 'w') as f:
        f.write(f"// Auto-generated by extract_text_and_bin2h.py\n")
        f.write(f"#pragma once\n")
        f.write(f"#include <cstdint>\n\n")
        f.write(f"constexpr size_t {array_name}_size = {len(payload_data)};\n\n")
        f.write(f"constexpr uint8_t {array_name}[{len(payload_data)}] = {{\n    ")

        for i, byte in enumerate(payload_data):
            f.write(f"0x{byte:02X}, ")
            if (i + 1) % 12 == 0:
                f.write("\n    ")

        f.write("\n};\n")

    print(f"Successfully generated {output_h} ({len(payload_data)} bytes).")

if __name__ == '__main__':
    main()
